#!/bin/sh
'''exec' "/Users/suniletikela/Dropbox/00. Software  Prep Dec 2021/Real Time Projects/Borrow4Less/venv/bin/python" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from django.core.management import execute_from_command_line
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(execute_from_command_line())
